apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: icrn-web-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "icrn.labels" . | nindent 4 }}
    app: icrn-web
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: icrn-web-service
                port:
                  number: 80
