apiVersion: v1
kind: Service
metadata:
  name: icrn-web-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "icrn.labels" . | nindent 4 }}
    app: icrn-web
spec:
  type: ClusterIP
  selector:
    app: icrn-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
