name: Test ICRN Manager

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq tar
        
    - name: Make scripts executable
      run: |
        chmod +x icrn_manager
        chmod +x update_r_libs.sh
        chmod +x tests/run_tests.sh
        
    - name: Run test suite
      run: |
        ./tests/run_tests.sh
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: tests/test_results.log
        
  test-docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: |
        docker build -t icrn-manager-test .github/docker/Rstudio/
        
    - name: Run tests in Docker
      run: |
        docker run --rm \
          -v $(pwd):/workspace \
          -w /workspace \
          icrn-manager-test \
          bash -c "cd /workspace && ./tests/run_tests.sh"
          
    - name: Upload Docker test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: docker-test-results
        path: tests/test_results.log 