apiVersion: v1
kind: Service
metadata:
  name: nginx-json-api
  labels:
    app: nginx-json-api
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080
  selector:
    app: nginx-json-api



